name: release 

on:
  release:
    types: [published]

jobs:
  deploy:
    concurrency: release
    runs-on: 'ubuntu-latest'
    if: github.run_attempt == 1

    steps:
      - name: Generate github token
        id: generate-github-token
        uses: tibdex/github-app-token@v1.8.0
        with:
            app_id: ${{ secrets.CLEVERTAP_CPE_BOT_ID }}
            private_key: ${{ secrets.CLEVERTAP_CPE_BOT_PRIVATE_ACCESS_KEY }}
      
      - name: Download release asset
        uses: robinraju/release-downloader@v1.8
        with:
          repository: CleverTap-CPE/keycloak
          tag: ${{ github.event.release.name }}
          fileName: account-fix-demo.zip
          token: ${{ steps.generate-github-token.outputs.token }}
      
      - name: Unzip release asset
        run: unzip account-fix-demo.zip && rm -rf account-fix-demo.zip
      
      - name: Copy Keycloak-Account-UI-Extension JAR to S3
        run: |
          aws s3 cp js/apps/account-ui/target/keycloak-account-ui-26.0.6.jar s3://production-global-management-eu-west-1-static-packages/rhkeycloak-packages/rhbk-26-upgrade/keycloak-account-ui-theme-26.0.6-${{ github.event.release.name }}.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
      
      - name: Copy Keycloak-Login-UI-Extension JAR to S3
        run: |
          aws s3 cp login-themes/target/keycloak-login-themes-26.0.6.jar  s3://production-global-management-eu-west-1-static-packages/rhkeycloak-packages/rhbk-26-upgrade/keycloak-login-theme-26.0.6-${{ github.event.release.name }}.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"